// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2G-KGfqhBsG-oxuRI1tyQs-oCGwiyfP8',
    appId: '1:1005931732324:web:dd9988f1de94fbf03eae71',
    messagingSenderId: '1005931732324',
    projectId: 'notas-app-e0ce7',
    authDomain: 'notas-app-e0ce7.firebaseapp.com',
    databaseURL: 'https://notas-app-e0ce7-default-rtdb.firebaseio.com',
    storageBucket: 'notas-app-e0ce7.firebasestorage.app',
    measurementId: 'G-V2N1YYDQPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1lJg6Ri5ilYArMarjfoe5Hijs4Dojcsc',
    appId: '1:1005931732324:android:3835aa73506452193eae71',
    messagingSenderId: '1005931732324',
    projectId: 'notas-app-e0ce7',
    databaseURL: 'https://notas-app-e0ce7-default-rtdb.firebaseio.com',
    storageBucket: 'notas-app-e0ce7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rXxEUbZ02Lxe-1P-ughMkYnefJh9MI4',
    appId: '1:1005931732324:ios:f55d998b7821a3873eae71',
    messagingSenderId: '1005931732324',
    projectId: 'notas-app-e0ce7',
    databaseURL: 'https://notas-app-e0ce7-default-rtdb.firebaseio.com',
    storageBucket: 'notas-app-e0ce7.firebasestorage.app',
    iosClientId: '1005931732324-egh3hi9ndp14fmpog5kn1lvjgv6c8h90.apps.googleusercontent.com',
    iosBundleId: 'com.example.notasApp',
  );
}
